### PR TITLE
Modified About Page, Nav Bar and side bar according to the pages

### LINKED ISSUE #756: Improving the About Page
Currently the About Page is looking like this , I will make it more interactive , and good looking one

image

### PR DESCRIPTION
**Pull request by pa1narendra**
Hey , this PR closes #756 issue , I modified and improved the about page, modified nav bar in necessary pages, and made the pages more simple with minor changes that improves user interactivity and ease of use. @avinash201199 can you please take a look at it and merge this asap. Let me know if any changes are required :)

### CODE REVIEW

**Comment by pa1narendra** [comment]
@avinash201199 is this going to take time to look into this

**Comment by avinash201199** [comment]
image
if you could beautify it here only then it will be more good ! 

Because the below design will look like out of the website 
image

**Comment by pa1narendra** [comment]
What should I do now , modify the design or not

**Comment by pa1narendra** [comment]
@avinash201199  here is the modified version of what you said , let me know if any more changes required

**Comment by pa1narendra** [comment]
@avinash201199 Can you please take a look at this and merge this PR

**Pull request merged**
