### PR TITLE
updated a course on UI/UX design

### PR DESCRIPTION
**Pull request by kritika-sharma130**
The course is offered by Google and is available on the platform Coursera.(Financial aid  is available so the course can be freely accessed).
#249

### CODE REVIEW

**Comment by kritika-sharma130** [comment]
Hii please merge my pull request.

**Comment by avinash201199** [comment]
as the name of the repo suggest free courses with certificates , please remove coursera course ,it's paid

**Comment by kritika-sharma130** [comment]
Please check the updated one!!

**Comment by avinash201199** [comment]
accepted your other pr , thank you

**Pull request closed without merging**
