### PR TITLE
fix: update PR to only add new React course

### PR DESCRIPTION
**Pull request by kaiyumdev**
fix: #748
- Removed unnecessary changes to unrelated files.
- Ensured that only the React course addition is included in this commit.
- Fixed issues with unintentional modifications to other lines.

### CODE REVIEW

**Comment by kaiyumdev** [comment]
@avinash201199 I have resolved the issues as requested, ensuring that only the new React course addition is included in this pull request. Could you kindly review the updated code? If there are any further issues, please let me know, and I will address them promptly. Otherwise, I would appreciate it if you could proceed with merging the pull request.

Thank you for your time and consideration!

**Comment by kaiyumdev** [comment]
@avinash201199 Could you please review my code at your convenience? If there are any further issues, I am happy to work on resolving them. Your feedback is appreciated, and I'll make any necessary changes promptly.

**Comment by avinash201199** [comment]
Thank you for your contribution !

**Comment by kaiyumdev** [comment]
Thank you for the opportunity! I'm glad to contribute, and I look forward to supporting the project further.

**Pull request merged**
