### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Akshra2020**
just added few new courses 😊Please see to it

### CODE REVIEW

**Comment by avinash201199** [comment]
you have to also add it in allcourses.json file , check contributing.md file

**Comment by Akshra2020** [comment]
Done sir.
Thank you so much sir for reaching out. I'm really thankful

**Comment by avinash201199** [comment]
you should have edited in this pr only , why to make two pr ?

**Comment by Akshra2020** [comment]
Thank you so much sir 🙏🌼
I'm really greatfull
And sorry for the inconvenience sir
Thanks a lot

**Pull request merged**
