### PR TITLE
feat: #748 Add New React Course to the React Courses Section

### PR DESCRIPTION
**Pull request by kaiyumdev**
feat #748
This pull request adds a new free React.js course to the React Courses section. Key highlights of the course:

- Comprehensive coverage of fundamental React concepts and best practices.
- Free access, making it accessible to a wider audience of learners.
- Includes certification upon completion, which is valuable for validating skills.
- Suitable for beginners and intermediate learners to strengthen their React.js knowledge.
- This course will be a valuable addition to the resource list, helping developers enhance their skills.

### CODE REVIEW

**Comment by kaiyumdev** [comment]
@avinash201199 Could you kindly review the code? If there are any issues or areas for improvement, please let me know and I will address them promptly. Otherwise, if everything looks good, I would appreciate it if you could merge the pull request.

**Comment by avinash201199** [comment]
> @avinash201199 Could you kindly review the code? If there are any issues or areas for improvement, please let me know and I will address them promptly. Otherwise, if everything looks good, I would appreciate it if you could merge the pull request.

You have made changes in so many lines shifted code up and down , due to that I'm not able to verify all the lines so I cannot accept this pr , you have to only insert the react one don't touch other lines 



https://github.com/user-attachments/assets/fdc3af42-d6f7-4034-83ce-0f5cecbe171a

I'm closing this pr , delete this repo and fork again and do the changes !

**Comment by kaiyumdev** [comment]
@avinash201199 Thank you for your feedback.

I understand the concern regarding unnecessary changes in other parts of the code. I will adjust the pull request to only insert the new React course without affecting other lines.

Once I’ve made the corrections, could you please review the updated code and proceed with the merge if everything looks good?

Thank you for your time and patience!

**Comment by avinash201199** [comment]
> @avinash201199 Thank you for your feedback.
> 
> I understand the concern regarding unnecessary changes in other parts of the code. I will adjust the pull request to only insert the new React course without affecting other lines.
> 
> Once I’ve made the corrections, could you please review the updated code and proceed with the merge if everything looks good?
> 
> Thank you for your time and patience!

Sure

**Pull request closed without merging**
