### PR TITLE
Adds Scaler - Javascript Certification Course

### PR DESCRIPTION
**Pull request by SoNiC-HeRE**
Adds an additional free course for Javascript from Scaler.
Updates Readme.md

### CODE REVIEW

**Comment by avinash201199** [comment]
also add in all course json file

**Comment by avinash201199** [comment]
?

**Comment by SoNiC-HeRE** [comment]
> ?

Sorry for the delay , I'll update it asap

**Comment by SoNiC-HeRE** [comment]
Hi @avinash201199 , pls let me know if more changes are required

**Pull request merged**
