### PR TITLE
Add Git Tutorial Course

### PR DESCRIPTION
**Pull request by karthikgowdams03**

### CODE REVIEW

**Comment by avinash201199** [comment]
you have to also add in readme file

**Comment by karthikgowdams03** [comment]
> you have to also add in readme file

It is already in the readme file so i didn't add it

**Comment by avinash201199** [comment]
the same course ?

**Comment by karthikgowdams03** [comment]
Yes

**Comment by karthikgowdams03** [comment]
I'll add a new course

**Pull request closed without merging**
