### PR TITLE
Search

### PR DESCRIPTION
**Pull request by HARDY8118**
Added search functionality

Fixed className typos

### CODE REVIEW

**Comment by avinash201199** [comment]
I checked the search functionality it's not working can you record a screen and add it here

**Comment by HARDY8118** [comment]
That seems unexpected, can you provide with some details.

**Comment by avinash201199** [comment]
image

No response on enter

**Comment by HARDY8118** [comment]
The problem seems with the special characters.
Capture
This is the expected behaviour.

Thanks for bringing this issue. I will fix this asap.

**Comment by avinash201199** [comment]
in my local system it's not working but let me accept the pr to check it's working or not

**Pull request merged**
