### PR TITLE
added functionality for closing search dropdown

### PR DESCRIPTION
**Pull request by Pavan-Rajesh**
when the user **clicks outside the dropdown will be closed** and also **added close button** for closing dropdown which is great user experience

### CODE REVIEW

**Comment by Pavan-Rajesh** [comment]
added Tailwind css for displaying the dashboard and also added the link from react router which does not do hard refresh and added icon for closing the side nav in the mobile view.

**Comment by avinash201199** [comment]
> added Tailwind css for displaying the dashboard and also added the link from react router which does not do hard refresh and added icon for closing the side nav in the mobile view.

can you please add ss or a small video of the ui changes

**Comment by Pavan-Rajesh** [comment]
https://drive.google.com/drive/folders/1Bm_irmz644t3L07OG25HfxKVW_WTiWBX?usp=sharing

**Comment by avinash201199** [comment]
> https://drive.google.com/drive/folders/1Bm_irmz644t3L07OG25HfxKVW_WTiWBX?usp=sharing
> 
> here is the video and see that there wont be any hard reloads when you navigate to other pages

That's awesome work , Thank you !

can you please give a button to go back to main page from dashboard!

**Pull request merged**
