### PR TITLE
Added new PowerBI courses

### PR DESCRIPTION
**Pull request by vipulSVJ**

### CODE REVIEW

**Review by vipulSVJ — COMMENTED** [review]
Hey @avinash201199 I have added the course review and merge it,

**Comment by vipulSVJ** [comment]
and please label it for hacktoberfest.

**Comment by avinash201199** [comment]
I can't accep this pr , you have formatted all the code in all course json file becaues of that I'm unable to review it , please create new pr and only add your code

**Comment by vipulSVJ** [comment]
Ok got it

**Pull request closed without merging**
