### PR TITLE
Added Prompt Engineering in Json file and also added new course Closes #723

### LINKED ISSUE #723: Add new course for Prompt Engineeering
Hey @avinash201199 there is only one course for Prompt Engineering . I would like to add one more for "Prompt Engineering for CharGPT" in that . Please assign it to me .

### PR DESCRIPTION
**Pull request by JatinPhogat**
- [X] I added the Prompt Engineering coursesin readme.mdwith proper links.
- [X] Added them in allcourses json file with links.
- [X] Created issue and starred the repo too.

Please accept this PR and instead of hactoberfest please mark this as label : feature .
Thankuu.

### CODE REVIEW

**Comment by avinash201199** [comment]
we are  not adding coursera courses as coursera do not provide free courses , to get free course we need to apply financial aid and it takes 16 days to verify

**Comment by JatinPhogat** [comment]
okay then can i create another issue regarding the same as Prompt enginerring is not mentioned in the .json file . i am participating in hacktoberfest and i need 2 pr ; ) . So can i make issue regarding that

**Comment by JatinPhogat** [comment]
@avinash201199 Thanks i understood , okay then can i create another issue regarding the same as Prompt enginerring is not mentioned in the .json file . i am participating in hacktoberfest and i need 2 pr ; ) . So can i make issue regarding that

**Comment by JatinPhogat** [comment]
okay ; )

**Pull request closed without merging**
