### PR TITLE
Fixed error in allcourses.json & added new course

### PR DESCRIPTION
**Pull request by PiyushDive**
I have fixed a error in allcourses.json file and added new course of Deep Learning

### CODE REVIEW

**Comment by avinash201199** [comment]
What was the error ?

**Comment by PiyushDive** [comment]
2 } & ]Brackets were missing I added them

**Comment by avinash201199** [comment]
okay but please edit that portion only , don't shift the space or anything because it shows changes in all the code , there is a conflict please resolve it

**Comment by PiyushDive** [comment]
Okay. It was fine after some merges it's showing it donno why I'll see

**Pull request closed without merging**
