### PR TITLE
#302 about page

### PR DESCRIPTION
**Pull request by Piratepie**
Added an about page following the steps laid out in #302 
https://user-images.githubusercontent.com/27888345/196641690-faf11797-eb5a-4c7f-88a0-84e945e2e06c.mp4

### CODE REVIEW

**Comment by Piratepie** [comment]
new pr in response to #303, changes limited to just about page elements

**Comment by avinash201199** [comment]
good work, can you please record the screen of about page working

**Comment by Piratepie** [comment]
Full pov of what about looks like (don't mind the muted colours, that's just my PC acting up)
https://user-images.githubusercontent.com/27888345/196930074-8398fff5-54a5-4f98-9b76-63a6208005d1.mp4

**Comment by avinash201199** [comment]
good work , will add more content in about page later on 
thank you for your contribution !

**Pull request merged**
