### PR TITLE
Added free DSA certificate course

### PR DESCRIPTION
**Pull request by ummeq**
Issue: #292 
This is 𝒇𝒓𝒆𝒆 𝒄𝒆𝒓𝒕𝒊𝒇𝒊𝒄𝒂𝒕𝒆 from 𝐆𝐨𝐨𝐠𝐥𝐞 Tech dev Guid by learning 𝐃𝐚𝐭𝐚 𝐒𝐭𝐫𝐮𝐜𝐭𝐮𝐫𝐞𝐬 𝐚𝐧𝐝 𝐀𝐥𝐠𝐨𝐫𝐢𝐭𝐡𝐦𝐬 with free practice material.
The course is available in four programming languages (Javascript, Java, C++ and Python)

### CODE REVIEW

**Comment by ummeq** [comment]
Hello @avinash201199  Avinash

Request you to please review and merge the PR

**Comment by avinash201199** [comment]
please add it in readme file also

**Comment by ummeq** [comment]
> please add it in readme file also

Okay sure thank you

**Comment by ummeq** [comment]
Hello @avinash201199 

I have add course link in readme file, request you to please review.

**Comment by avinash201199** [comment]
Good , thank you :)

**Pull request merged**
