### PR TITLE
Aws skill builder Course for cloud Practitioner 

### PR DESCRIPTION
**Pull request by HeYPoonam**
#https://github.com/avinash201199/Free-courses-with-Certificates/issues/253

### CODE REVIEW

**Comment by HeYPoonam** [comment]
@avinash201199 Only I make 2PR in this repo 1is accepted & this one is remaining please consider it.

**Comment by avinash201199** [comment]
please resolve conflicts

**Comment by avinash201199** [comment]
any updates ?

**Comment by HeYPoonam** [comment]
I did not understand the issue of conflict & trying to resolve it.

**Comment by avinash201199** [comment]
then please delete the repo and fork again to do your changes

**Pull request closed without merging**
