### PR TITLE
Adding New Course: Scala

### PR DESCRIPTION
**Pull request by khushminder270**

### CODE REVIEW

**Comment by avinash201199** [comment]
also add in readme file

**Comment by khushminder270** [comment]
@avinash201199  Added in readme file

**Comment by khushminder270** [comment]
@avinash201199 please add **hactoberfest-accepted** label to the PR

**Comment by avinash201199** [comment]
hey , there was major bug , due to that I have reverted few pr , please create new pr  to resolve this conflict

**Pull request closed without merging**
