### PR TITLE
modified the footer

### PR DESCRIPTION
**Pull request by SoulNikhar**

### CODE REVIEW

**Comment by avinash201199** [comment]
> hey bro this is updated footer section please review it and accept my PR

please add the screenshot of the ui changes

**Comment by SoulNikhar** [comment]
Ya sure.
Will I  add screenshot tomorrow??

**Comment by SoulNikhar** [comment]
Here is the updated footer  @avinash201199  
PreFooter
updatedFooter

**Comment by avinash201199** [comment]
thank you for you contribution

**Comment by SoulNikhar** [comment]
Thanks @avinash201199 for accepting my PR. 
1. U already assigned me sidebar section (currently working on it)
2. Their are numerous errors in allcourse.json . Will u assign it to me.

**Pull request merged**
