### PR TITLE
[Hacktoberfest'23] : Added Operating System Course

### PR DESCRIPTION
**Pull request by Ash0807**
# Title and Issue number 
This PR contains the source of added "Operating system Course" : https://github.com/avinash201199/Free-courses-with-Certificates/issues/431
Close : https://github.com/avinash201199/Free-courses-with-Certificates/issues/431

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by avinash201199** [comment]
image
you need to add free course with certificates , also you have to add Alphabetical order in the readme file + all course json file

**Comment by Ash0807** [comment]
Done @avinash201199 , I have completed all the required changes for this pull request. Could you please review and merge my pull request with the **Hacktoberfest** label ?

**Comment by avinash201199** [comment]
Thank you for your contribution :)

**Comment by Ash0807** [comment]
Thanks @avinash201199 for merging my pull request.

**Pull request merged**
